import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Box, ArrowUpRight, Search, Plus, X, Activity, CheckCircle2, AlertTriangle, Clock3, RefreshCw, ChevronRight } from 'lucide-react';
import type { Case, Status } from '../server/store';
import './style.css';
async function api<T>(path:string, options:RequestInit={}):Promise<T> {
  const response=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});
  const body=await response.json(); if(!response.ok) throw new Error(body.error || 'Request failed'); return body;
}
function App(){
 const [items,setItems]=useState<Case[]>([]),[selected,setSelected]=useState<Case|null>(null),[events,setEvents]=useState<{id:number;message:string;createdAt:string}[]>([]);
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[severity,setSeverity]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[showNew,setShowNew]=useState(false),[note,setNote]=useState(''),[owner,setOwner]=useState('');
 async function load(){try{setError('');const rows=await api<Case[]>('/cases');setItems(rows);return rows;}catch(e){setError((e as Error).message);return [];}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!selected)return;let active=true;setOwner(selected.owner);setNote('');setEvents([]);api<typeof events>(`/cases/${selected.id}/events`).then(rows=>{if(active)setEvents(rows);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected?.id,selected?.version]);
 async function update(next?:Status){if(!selected)return;setBusy(true);try{const updated=await api<Case>(`/cases/${selected.id}`,{method:'PATCH',body:JSON.stringify({version:selected.version,status:next,owner,note:note||undefined})});setSelected(updated);await load();}catch(e){setError((e as Error).message);if((e as Error).message.includes('Refresh')){const rows=await load();setSelected(rows.find(r=>r.id===selected.id)||null);}}finally{setBusy(false);}}
 const visible=items.filter(c=>(!status||c.status===status)&&(!severity||c.severity===severity)&&`${c.title} ${c.orderId} ${c.facility}`.toLowerCase().includes(query.toLowerCase()));
 const active=items.filter(c=>c.status!=='resolved');const overdue=active.filter(c=>new Date(c.dueAt).getTime()<Date.now());
 const metrics=[['Active exceptions',active.length,Box,'Across all facilities'],['High priority',active.filter(c=>c.severity==='high').length,AlertTriangle,'Needs focused attention'],['Past due',overdue.length,Clock3,'Recovery target exceeded'],['Resolved',items.filter(c=>c.status==='resolved').length,CheckCircle2,'Closed with an audit trail']] as const;
 return <div className="shell"><aside className="rail"><a className="mark" href="#" aria-label="Fulfillment Control home"><Box size={26}/></a><div className="rail-active"><Activity size={21}/></div><div className="rail-bottom">FC</div></aside><main><header><div className="crumb">WORKSPACE <ChevronRight size={13}/> OPERATIONS</div><span className="local"><i/> Local demo</span></header><section className="intro"><div><p className="eyebrow">FULFILLMENT CONTROL / 01</p><h1>Keep every order<br/><span>moving forward.</span></h1><p>Investigate exceptions. Coordinate recovery. Close the loop.</p></div><button className="primary" onClick={()=>setShowNew(true)}><Plus size={17}/> New exception</button></section>
 <section className="metrics">{metrics.map(([title,value,Icon,hint])=><article key={title}><div><span>{title}</span><Icon size={18}/></div><strong>{loading?'—':value}</strong><small>{hint}</small></article>)}</section>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 <section className="queue"><div className="queue-head"><div><h2>Exception queue <span>{visible.length}</span></h2><p>Prioritized by severity, then recovery target.</p></div><button className="subtle" onClick={()=>void load()} aria-label="Refresh cases"><RefreshCw size={16}/></button></div><div className="filters"><label className="search"><Search size={17}/><input aria-label="Search cases" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, issue, or facility"/></label><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option></select><select aria-label="Filter priority" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All priorities</option><option>high</option><option>medium</option><option>low</option></select></div>
 <div className="table-wrap"><table><thead><tr><th>EXCEPTION / ORDER</th><th>FACILITY</th><th>PRIORITY</th><th>STATUS</th><th>OWNER</th><th></th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><button className="case-title" onClick={()=>{setError('');setSelected(c);}}>{c.title}</button><small>{c.orderId}</small></td><td>{c.facility}</td><td><span className={`priority ${c.severity}`}><i/>{c.severity}</span></td><td><span className={`status ${c.status}`}>{c.status}</span></td><td>{c.owner||'Unassigned'}</td><td><button aria-label={`Open ${c.orderId}`} className="subtle" onClick={()=>setSelected(c)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">{loading?'Loading your workspace…':'No exceptions match this view.'}</div>}</div></section><footer>Synthetic demo data · Persistent SQLite storage <span>Designed & built by Ramesh Yenduri</span></footer></main>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="case-heading" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close case" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">{selected.orderId} / CASE DETAILS</p><h2 id="case-heading">{selected.title}</h2><p>{selected.facility}</p><div className="detail-line"><span className={`priority ${selected.severity}`}>{selected.severity} priority</span><span className={`status ${selected.status}`}>{selected.status}</span></div><p className="due">Recovery target: {new Date(selected.dueAt).toLocaleString()}</p><label>Owner<input value={owner} maxLength={60} onChange={e=>setOwner(e.target.value)} placeholder="Assign an owner"/></label><label>Investigation / resolution note<textarea rows={4} value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="What happened, and what is the next step?"/></label>{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><button className="secondary" disabled={busy} onClick={()=>void update()}>Save note / owner</button><button className="primary" disabled={busy} onClick={()=>void update(selected.status==='investigating'?'resolved':'investigating')}>{selected.status==='open'?'Investigate':selected.status==='investigating'?'Resolve case':'Reopen case'}</button></div><h3>Activity trail</h3><ol className="timeline">{events.map(e=><li key={e.id}><p>{e.message}</p><time>{new Date(e.createdAt).toLocaleString()}</time></li>)}</ol><small>Version {selected.version} · Conflicting edits are rejected.</small></section></div>}
 {showNew&&<div className="overlay"><form className="drawer" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);try{const item=await api<Case>('/cases',{method:'POST',body:JSON.stringify({title:data.get('title'),orderId:data.get('orderId'),facility:data.get('facility'),severity:data.get('severity'),owner:'',dueAt:new Date(String(data.get('dueAt'))).toISOString()})});setShowNew(false);setSelected(item);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><button type="button" className="close" aria-label="Close new exception" onClick={()=>setShowNew(false)}><X/></button><p className="eyebrow">OPEN A CASE</p><h2>New exception</h2><label>Issue<input name="title" required minLength={4} maxLength={160}/></label><label>Order ID<input name="orderId" required maxLength={40}/></label><label>Facility<input name="facility" required maxLength={80}/></label><label>Priority<select name="severity"><option value="medium">Medium</option><option value="high">High</option><option value="low">Low</option></select></label><label>Recovery target<input name="dueAt" type="datetime-local" required/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>Create exception</button></form></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
